import Head from 'next/head';
import About from '../components/about';
import Features from '../components/features';
import Hero from '../components/hero';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta
          name="description"
          content="Profile Company website generated by create next app"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className="bg-hero px-[105px]">
        <Hero />
      </header>
      <About />
      <Features />

      <footer></footer>
    </>
  );
}
